# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Cg627jWnB86gPmkv0w_H4y2Rg-RQM0H
"""



"""# 1. Find out all the types of error that we have encountered in our lecture and why? Also include the examples.

##### Different types of error we faced are:-
1) Name Error:- We tried to print a variable which we did not initialize. Eg is given below
"""

a = 3
b = 4
print(c)

"""#### 2) Type Error: - We tried to assign a variable to a reserved word. """

print = "Hello"
type(print)

print("Hello")

del print

"""#### 3) Type Error: - We tried to perform artithmetical operations on string. When we use input function then the variable is assigned with a string even a integer is entered. In order to deal with this we always have to initialize the input variables as integer before performing arithmetic operations on it. """

a = input("Enter 1st Number:- ")
b = input("Enter 2nd Number:- ")
sub = a - b
print(sub)

#The solution is
c = int(input("Enter 1st Number:- "))
d = int(input("Enter 2nd Number:- "))

subst = c - d
print(subst)

"""#### 4) Syntax Error: -  This error occured when we entered a invalid syntax.

"""

int A

"""#### 5) Value Error: This error occurs when we enter invalid values for a assigned variable. For eg entering a float in int. This error also occurs when we try to convert a float value to int or a string value to float or int."""

a = int(input("Enter Number"))
print(a)

"""# 2) Take input A and B and print their sum, mul, div, square of the nos."""

a = int(input("Please enter the first Number:- "))
b = int(input("Please enter the second Number:- "))
print(f"The Sum of {a} and {b} is",(a+b))
print(f"The multiplication of {a} and {b} is",(a*b))
print(f"The division of {a} divided by {b} is",(a/b))
print(f"The square of {a} and {b} is",(a**2),"and",(b**2))

"""# 3) How many reserve keywords are there in python and why we should not use them as a variable name?

There are 33 reserve words in python. We should not use the reserved words for a variable name in python because python will not allow it and we may get an error. Also these reserve words serve a specific purpose. They are used to give specific programming instructions.

# Create email ids with the user inputs. in the following format - lastname.firstname@gmail.com
"""

lname = input("Enter your last name:- ")
fname = input("Enter your first name:- ")
print(f"Your emaiL address is {lname.lower()}.{fname.lower()}@gmail.com")

"""# 5)Try to print the following lines -
Hi I'm Sunny
My address is 22\3
I earn 20$ daily.
"""

name = input("Enter your Name:- ")
add = input('Enter your address:- ')
earn =(input("Enter your daily earnings:- "))
print(f"""
My Name is {name}
I live at {add}
I daily earn {earn} daily
""")

"""# 7) Convert the following -
"22.4" into integer
"22" into complex no.
"""

a = 22.4
print(f"Before conversion type is {type(a)} and value of a is {a}")
a = int(a)
print(f"After concersion type is {type(a)} and value of a is {a}")

b = 22
print(f"Before conversion type is {type(b)} and value of a is {b}")
b = complex(b)
print(f"After concersion type is {type(b)} and value of a is {b}")